# Generated by Django 5.2 on 2025-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('General Medicine', 'General')], default='General Medicine', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
